[build-system]
requires = ["setuptools>=68", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "krcg"
dynamic = ["version"]
authors = [
    { name = "Lionel Panhaleux", email = "lionel.panhaleux+krcg@gmail.com" },
]
description = "Library for VTES cards and TWDA."
keywords = ["vtes", "Vampire: The Eternal Struggle", "CCG", "TWD", "TWDA"]
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "arrow",
    "pyyaml",
    "numpy",
    "requests",
    "setuptools",
    "unidecode",
]

[project.optional-dependencies]
dev = [
    "certifi",
    "coverage",
    "codacy-coverage",
    "black",
    "ipython",
    "pytest",
    "ruff",
    "yamllint",
    "zest.releaser[recommended]",
]

[project.urls]
Repository = "https://github.com/lionel-panhaleux/krcg"

[tool.setuptools.packages.find]
include = ["krcg*"]

# required for dynamic version
[tool.setuptools_scm]

[tool.zest-releaser]
create-wheel = true
